# Generated by Django 4.2.3 on 2023-07-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
