# Generated by Django 4.2.3 on 2023-07-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
    ]
