# Generated by Django 4.2.3 on 2023-08-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_remove_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='images',
        ),
        migrations.AddField(
            model_name='listings',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='listings_images/<autoslug.fields.AutoSlugField>/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/<autoslug.fields.AutoSlugField>/'),
        ),
        migrations.AddField(
            model_name='listings',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/<autoslug.fields.AutoSlugField>'),
        ),
    ]
