# Generated by Django 4.2.3 on 2023-08-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_alter_listings_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
